export const weapons = [
  {
    name: "Reinforcement",
    type: "Unarmed",
    damage: "d4",
    range: "0",
    integrity: 6,
    size: 0,
    reach: 1,
    fatigue: 1,
    magic: 0,
    critical: "M/S",
    magical: false,
    ranged: false,
  },
  {
    name: "Combat Knife",
    type: "Melee",
    damage: "d4",
    range: "1",
    integrity: 6,
    size: 1,
    reach: 1,
    fatigue: 2,
    magic: 0,
    critical: "D/S",
    magical: false,
    ranged: false,
  },
  {
    name: "Fire Axe",
    type: "Melee",
    damage: "d8",
    range: "0",
    integrity: 6,
    size: 2,
    reach: 1,
    fatigue: 4,
    magic: 0,
    critical: "D",
    magical: false,
    ranged: false,
  },
  {
    name: "Machete",
    type: "Melee",
    damage: "d6",
    range: "0",
    integrity: 3,
    size: 2,
    reach: 1,
    fatigue: 2,
    magic: 0,
    critical: "D/S",
    magical: false,
    ranged: false,
  },
  {
    name: "Riot Shield",
    type: "Melee",
    damage: "d4",
    range: "0",
    integrity: 12,
    size: 3,
    reach: 1,
    fatigue: 3,
    magic: 0,
    critical: "M",
    magical: false,
    ranged: false,
  },
  {
    name: "Pistol",
    type: "Handguns",
    damage: "d6",
    range: "1",
    integrity: 3,
    size: 1,
    reach: 1,
    fatigue: 1,
    magic: 0,
    critical: "D/S",
    magical: false,
    ranged: true,
  },
  {
    name: "Revolver",
    type: "Handguns",
    damage: "d8",
    range: "1",
    integrity: 6,
    size: 1,
    reach: 1,
    fatigue: 2,
    magic: 0,
    critical: "D",
    magical: false,
    ranged: true,
  },
  {
    name: "SMG",
    type: "Handguns",
    damage: "d6",
    range: "1",
    integrity: 3,
    size: 2,
    reach: 1,
    fatigue: 2,
    magic: 0,
    critical: "M/S",
    magical: false,
    ranged: true,
  },
  {
    name: "Assault Rifle",
    type: "Machinegun",
    damage: "d8",
    range: "2",
    integrity: 6,
    size: 2,
    reach: 1,
    fatigue: 3,
    magic: 0,
    critical: "D/M",
    magical: false,
    ranged: true,
  },
  {
    name: "Heavy Machinegun",
    type: "Machinegun",
    damage: "d10",
    range: "2",
    integrity: 9,
    size: 3,
    reach: 1,
    fatigue: 4,
    magic: 0,
    critical: "D",
    magical: false,
    ranged: true,
  },
  {
    name: "Hunting Rifle",
    type: "Rifle",
    damage: "d8",
    range: "3",
    integrity: 6,
    size: 2,
    reach: 1,
    fatigue: 3,
    magic: 0,
    critical: "S",
    magical: false,
    ranged: true,
  },
  {
    name: "Sniper Rifle",
    type: "Rifle",
    damage: "d10",
    range: "3",
    integrity: 6,
    size: 2,
    reach: 1,
    fatigue: 3,
    magic: 0,
    critical: "D",
    magical: false,
    ranged: true,
  },
  {
    name: "Pump-Action Shotgun",
    type: "Shotgun",
    damage: "d8",
    range: "2",
    integrity: 9,
    size: 2,
    reach: 1,
    fatigue: 4,
    magic: 0,
    critical: "D",
    magical: false,
    ranged: true,
  },
  {
    name: "Double-Barrel Shotgun",
    type: "Shotgun",
    damage: "d12",
    range: "1",
    integrity: 9,
    size: 2,
    reach: 1,
    fatigue: 5,
    magic: 0,
    critical: "D/S",
    magical: false,
    ranged: true,
  },
  {
    name: "Grenade Launcher",
    type: "Artillery",
    damage: "d12",
    range: "2",
    integrity: 6,
    size: 3,
    reach: 1,
    fatigue: 5,
    magic: 0,
    critical: "D/S",
    magical: false,
    ranged: true,
  },
  {
    name: "Flamethrower",
    type: "Artillery",
    damage: "d20",
    range: "1",
    integrity: 3,
    size: 3,
    reach: 1,
    fatigue: 4,
    magic: 0,
    critical: "D",
    magical: false,
    ranged: true,
  },
];

export const stuff = [{ name: "Food" }];

export const skills = [
  // COMBAT
  {
    name: "Unarmed",
    base: ["str", "con"],
  },
  {
    name: "Melee",
    base: ["str", "dex"],
  },
  {
    name: "Handguns",
    base: ["dex", "int"],
  },
  {
    name: "Machinegun",
    base: ["dex", "str"],
  },
  {
    name: "Rifle",
    base: ["dex", "int"],
  },
  {
    name: "Shotgun",
    base: ["str", "con"],
  },
  {
    name: "Artillery",
    base: ["str", "siz"],
  },
  // GENERAL
  {
    name: "Evade",
    base: ["dex", "dex"],
  },
  {
    name: "Stealth",
    base: ["dex", "int"],
  },
  {
    name: "Survival",
    base: ["con", "int"],
  },
  {
    name: "Biotech",
    base: ["int", "int"],
  },
  {
    name: "Technical",
    base: ["int", "pow"],
  },
];
