export const weapons = [
  // landing page needs custom roll for skills and damage
  // BLADES
  {
    name: "Dagger",
    type: "Blades",
    damage: "d4",
    range: "1",
    integrity: 3,
    size: 1,
    reach: 1,
    fatigue: 1,
    magic: 0,
    critical: "D/S",
    magical: false,
  },
  {
    name: "Short Sword",
    type: "Blades",
    damage: "d6",
    range: "0",
    integrity: 6,
    size: 1,
    reach: 1,
    fatigue: 1,
    magic: 0,
    critical: "D/M/S",
    magical: false,
  },
  {
    name: "Long Sword",
    type: "Blades",
    damage: "d8",
    range: "0",
    integrity: 6,
    size: 2,
    reach: 2,
    fatigue: 2,
    magic: 0,
    critical: "D/M",
    magical: false,
  },
  {
    name: "Great Sword",
    type: "Blades",
    damage: "d10",
    range: "0",
    integrity: 9,
    size: 3,
    reach: 2,
    fatigue: 3,
    magic: 0,
    critical: "D/M",
    magical: false,
  },

  // POLEARMS
  {
    name: "Quarterstaff",
    type: "Polearms",
    damage: "d6",
    range: "0",
    integrity: 6,
    size: 3,
    reach: 2,
    fatigue: 1,
    magic: 0,
    critical: "M/S",
    magical: false,
  },
  {
    name: "Spear",
    type: "Polearms",
    damage: "d6",
    range: "2",
    integrity: 6,
    size: 3,
    reach: 2,
    fatigue: 1,
    magic: 0,
    critical: "D/M",
    magical: false,
  },
  {
    name: "Poleblade",
    type: "Polearms",
    damage: "d8",
    range: "0",
    integrity: 6,
    size: 3,
    reach: 3,
    fatigue: 2,
    magic: 0,
    critical: "D/M",
    magical: false,
  },

  // SHIELDS
  {
    name: "Buckler",
    type: "Shields",
    damage: "d4",
    range: "0",
    integrity: 6,
    size: 1,
    reach: 1,
    fatigue: 1,
    magic: 0,
    critical: "M/S",
    magical: false,
  },
  {
    name: "Shield",
    type: "Shields",
    damage: "d6",
    range: "0",
    integrity: 9,
    size: 2,
    reach: 1,
    fatigue: 2,
    magic: 0,
    critical: "D/S",
    magical: false,
  },

  // HEAVIES
  {
    name: "Hand Axe",
    type: "Heavies",
    damage: "d6",
    range: "1",
    integrity: 6,
    size: 1,
    reach: 1,
    fatigue: 1,
    magic: 0,
    critical: "D/S",
    magical: false,
  },
  {
    name: "Club",
    type: "Heavies",
    damage: "d8",
    range: "1",
    integrity: 9,
    size: 2,
    reach: 1,
    fatigue: 2,
    magic: 0,
    critical: "D/S",
    magical: false,
  },
  {
    name: "Battleaxe",
    type: "Heavies",
    damage: "d10",
    range: "0",
    integrity: 9,
    size: 3,
    reach: 2,
    fatigue: 3,
    magic: 0,
    critical: "D/S",
    magical: false,
  },

  // RANGED
  {
    name: "Sling",
    type: "Ranged",
    damage: "d4",
    range: "2",
    integrity: 3,
    size: 1,
    reach: 0,
    fatigue: 1,
    magic: 0,
    critical: "D/S",
    magical: false,
  },
  {
    name: "Bow",
    type: "Ranged",
    damage: "d6",
    range: "3",
    integrity: 6,
    size: 3,
    reach: 0,
    fatigue: 2,
    magic: 0,
    critical: "D/M",
    magical: false,
  },

  // UNARMED
  {
    name: "Gauntlet",
    type: "Unarmed",
    damage: "d4",
    range: "0",
    integrity: 3,
    size: 1,
    reach: 1,
    fatigue: 0,
    magic: 0,
    critical: "M/S",
    magical: false,
  },

  // MIND
  {
    name: "Mind Projection Tiara",
    type: "Mind",
    damage: "d6",
    range: "3",
    integrity: 3,
    size: 1,
    reach: 0,
    fatigue: 1,
    magic: 1,
    critical: "M/S",
    magical: true,
  },

  // ENERGY
  {
    name: "Energy Wand",
    type: "Energy",
    damage: "d6",
    range: "2",
    integrity: 3,
    size: 1,
    reach: 0,
    fatigue: 1,
    magic: 1,
    critical: "D/S",
    magical: true,
  },
  {
    name: "Energy Staff",
    type: "Energy",
    damage: "d8",
    range: "3",
    integrity: 6,
    size: 3,
    reach: 2,
    fatigue: 2,
    magic: 1,
    critical: "D/M",
    magical: true,
  },

  // ALCHEMY
  {
    name: "Explosive Concoction",
    type: "Alchemy",
    damage: "d8",
    range: "2",
    integrity: 3,
    size: 1,
    reach: 0,
    fatigue: 1,
    magic: 1,
    critical: "D/S",
    magical: true,
  },

  // FIRE
  {
    name: "Living Flame Scepter",
    type: "Fire",
    damage: "d8",
    range: "2",
    integrity: 3,
    size: 2,
    reach: 1,
    fatigue: 1,
    magic: 1,
    critical: "D/S",
    magical: true,
  },

  // THUNDER
  {
    name: "Thunderstone Rings",
    type: "Thunder",
    damage: "d8",
    range: "2",
    integrity: 3,
    size: 1,
    reach: 1,
    fatigue: 2,
    magic: 1,
    critical: "D/S",
    magical: true,
  },

  // WIND
  {
    name: "Cloudfeather Fan",
    type: "Wind",
    damage: "d6",
    range: "3",
    integrity: 3,
    size: 2,
    reach: 1,
    fatigue: 1,
    magic: 1,
    critical: "M/S",
    magical: true,
  },
];

export const stuff = [{ name: "Food" }];

export const skills = [
  // General
  {
    name: "Athletics",
    base: ["str", "con"],
  },
  {
    name: "Survival",
    base: ["dex", "int"],
  },
  {
    name: "Evade",
    base: ["con", "dex"],
  },
  {
    name: "Eloquence",
    base: ["int", "pow"],
  },
  {
    name: "Knowledge",
    base: ["int", "int"],
  },
  {
    name: "Endurance",
    base: ["con", "con"],
  },

  // Combat
  {
    name: "Blades",
    base: ["str", "dex"],
  },
  {
    name: "Heavies",
    base: ["str", "siz"],
  },
  {
    name: "Polearms",
    base: ["con", "dex"],
  },
  {
    name: "Ranged",
    base: ["dex", "dex"],
  },
  {
    name: "Shields",
    base: ["str", "con"],
  },
  {
    name: "Unarmed",
    base: ["dex", "pow"],
  },

  // Magic
  {
    name: "Mind",
    base: ["int", "int"],
  },
  {
    name: "Energy",
    base: ["int", "con"],
  },
  {
    name: "Alchemy",
    base: ["int", "pow"],
  },
  {
    name: "Fire",
    base: ["pow", "pow"],
  },
  {
    name: "Thunder",
    base: ["pow", "con"],
  },
  {
    name: "Wind",
    base: ["pow", "dex"],
  },
];
